spring.application.name=HoloRoom
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_RUU-CR7dEDkDB3yqzo_@mysql-ccc017a-abderahim-f51b.k.aivencloud.com:18127/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_RUU-CR7dEDkDB3yqzo_

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect